lib/sniff/run-html-codesniffer.js, package.json, test/unit/sniff/run-html-codesniffer.js
Fixes the issue outlined in #45. @mfairchild365, could you verify this?
=> Fix zombie process issues

README.md, bin/pa11y
=> add the ability to set the number of errors to allow before failing

README.md, bin/pa11y, test/integration/cli-ignore.js
use commander coercion to allow repeatable ignore options
=> Multiple ignore options

README.md, bin/pa11y, lib/inject.js, lib/pa11y.js, test/integration/cli-root-element.js, test/integration/mock/html/root-element.html, test/unit/lib/inject.js, test/unit/lib/pa11y.js, test/unit/mock/window.js
Allows you to test a part of the page and ignore everything outside of it.
I wanted to raise this PR to get some feedback on the naming before tidying up and putting in the tests.
I was struggling with the option name and I am not sure how people feel about `selector` ?
=> Adds ability to define testing area

CHANGELOG.md
As part of a consistency exercise among pa11y projects.
=> Rename HISTORY to CHANGELOG

CHANGELOG.md, MIGRATION.md, README.md, example/basic/index.js, example/before-script/index.js, example/multiple-concurrent/index.js, example/multiple/index.js, package.json
Addresses https://github.com/pa11y/org/issues/4
=> Rename all the repos and uppercase Pa11y

.travis.yml, MIGRATION.md, README.md, package.json
I've changed the support levels for now, we can make any ES6 updates in a later PR. Resolves #159.
=> Release 4.0.0

README.md, bin/pa11y
and adjusted help info, for clarity
=> added threshold example

README.md, bin/pa11y
sorry i made a couple of really derpy mistakes :/
=> fixed derps

README.md
Add latest stable recommendation to the docs.
Resolves #123.
=> add recommendation

MIGRATION.md, README.md
=> #181 | Fixed spelling errors in markdown files

package.json
Use [Truffler 2.3.x](https://github.com/springernature/truffler/blob/master/CHANGELOG.md#230-2016-11-08) This should make Phantom issues a little easier to debug.
=> Bump Truffler version

README.md
=> Add protocols to URLs, make path instructions explicit

README.md, lib/pa11y.js, package.json
Reopening #190 in a place where I can make a few tweaks
=> Install phantomjs as a dependency

README.md
=> Sunset Pa11y v2

lib/pa11y.js, package.json, test/unit/lib/pa11y.js
Truffler 3.0 includes some breaking changes, hence the code and test changes in here.
=> Upgrade Truffler to version 3.0

test/integration/cli-basic.js, test/integration/cli-config.js, test/integration/cli-hide-elements.js, test/integration/cli-ignore.js, test/integration/cli-level.js, test/integration/cli-root-element.js, test/integration/cli-selector.js, test/integration/cli-standard.js, test/integration/cli-threshold.js, test/integration/setup.js, test/unit/setup.js
Realized I missed a few unnecessary disable flags in the previous PR (#220) I opened regarding #218.
=> Cleans up remaining jshint and jscs disable flags

.gitignore, README.md, bin/pa11y.js, lib/pa11y.js, test/integration/cli-screen-capture.js, test/unit/lib/pa11y.js, test/unit/mock/phantom.js
This will be useful for the following:
- Verifying that the page you tested is what you expect
- Looking for parts of the page that change between tests (giving
inconsistent results)
=> Add the ability to screen capture the tested page

TROUBLESHOOTING.md
I broke a bunch of stuff. I've fixed the stuff I broke, and also made the linking method consistent.
=> fix the link catastrophe I just created

README.md
It's now less pessimistic, because it turns out Windows 10 setup is pretty easy.
=> Update the Windows requirements

.editorconfig, .gitignore, .travis.yml, Makefile, Makefile.node, README.md, package.json
This updates a load of our tooling and now Pa11y is consistent with CI/Sidekick – more modern projects. This may be easier to grok by looking into each commit individually.
=> Tooling update

package.json, test/unit/lib/action.js, test/unit/lib/pa11y.js
Now using caret versions for everything. This is generally safe to do,
and all of the dependencies we use are mature enough to not be
introducing breaking changes under minor/patch releases.
Also I've made sure that https://nightli.es/ runs for all of the Pa11y
projects so that we're alerted early if a dependency ever does start to
fail the build.
=> Update all of the dependencies

README.md, example/basic/index.js, example/multiple/index.js, test/integration/mock/html/hide-elements.html
* Updated references in README from nature.com to example.com
* Updated examples to use example.com instead of nature.com
* Updated  mock html document to use pa11y url instead of nature.com
=> [Feature] updated example urls (#252)

README.md, bin/pa11y.js, reporter/tsv.js, test/integration/cli-reporter-tsv.js
=> Tsv reporter

README.md
Resolves #264 - instead of adding additional examples, let's link to some query selector docs to make it more obvious that you can use any query selector you like
=> clarify actions in readme

TROUBLESHOOTING.md, package.json
Pa11y now supports non-GET requests.
=> Bump the minimum Truffler version

TROUBLESHOOTING.md
=> Document how to authenticate with basic auth

README.md, lib/reporter/cli.js, lib/runner.js, test/unit/lib/runner.js, test/unit/mock/window.js
This closes #164, which has been hanging around for AGES.
=> Output the final URL in the CLI reporter

README.md
We can probably close #308 once merged.
=> Add a note to the support end date for Pa11y 4.x

MIGRATION.md, README.md
These are now complete, as all of the mentioned reporters have been
published. Resolves #299
=> Remove TODO items from the reporter documentation

README.md
=> remove survey, add 5.0 beta

bin/pa11y.js, package-lock.json, package.json
=> Update Puppeteer and remove hack

lib/pa11y.js, test/unit/lib/pa11y.js
Fixes an error that doesn't allow to set the `timeout` option for more than 30 seconds.
=> Fix 5.x timeout

README.md
reopening https://github.com/pa11y/pa11y/pull/344
=> Update readme to make explicit what the timeout includes

package-lock.json, package.json
We're having Chromium crashes on Windows, thought this might help.
=> Update to puppeteer@1.0.0

package-lock.json, package.json, test/integration/issue/373.test.js, test/integration/mock/html/issue/373.html
This fixes #373 and adds in a test to ensure it won't regress.
=> Use the latest version of the CLI reporter

README.md, example/puppeteer/index.js, lib/pa11y.js, test/unit/lib/pa11y.test.js
This also ensures that an error is thrown if you attempt to use the page
option without the browser option.
@eloytoro possibly you'd like to take a look at this?
=> Add documentation for the page option

README.md, example/actions/index.js, example/basic/index.js, example/multiple/index.js
This makes them consistent with the new Puppeteer example, and is also a
nicer interface.
=> Update the examples to use async/await

TROUBLESHOOTING.md
This removes an existing TODO and satisfies https://github.com/pa11y/pa11y/issues/303
=> Answer troubleshooting question for using a proxy server

package.json
This fixes the issue documented here: https://github.com/GoogleChrome/puppeteer/issues/1506
I've opened an issue to unpin the version once a fix is released: #393
=> Pin puppeteer at 1.0.0

package-lock.json, package.json
Did not commit `package-lock.json` since it seemed to have so many other changes...
=> Seems like Mocha v6 can be used without any changes

README.md, package-lock.json, package.json
There was a puppeteer vulnerability patched in version 1.13.0, this updates the package.json file accordingly.
=> Bump puppeteer version

MIGRATION.md, README.md
Including but not limited to:
* Update the status of pa11y v4 in the readme (unsupported since August 2018)
* Update copyright date
* Update Koa11y notice
* Update words
=> Minor documentation updates

lib/pa11y.js, package-lock.json, package.json
Also fixes two issues introduced by the new [require-atomic-updates](https://eslint.org/docs/rules/require-atomic-updates) rule.
=> Update eslint to v6

README.md, package-lock.json, package.json
Also removes an extra space from the README.
=> Update sinon to v7

README.md
I'll create another PR reverting this change, to be merged in around two weeks from 12th August.
=> Add our design survey to the README

bin/pa11y.js
There's a bunch of functions on this file, so now at least it will be easier to understand what each one of them is doing, as there are no unit tests for them.
=> Add some JSDoc to bin/pa11y.js

package-lock.json, package.json
Resolves #481 
Couldn't see any breaking changes that affect code, unit tests run successfully and running a few tests manually run as expected.
=> updated command to v3.0.2

CHANGELOG.md, package-lock.json, package.json
Finally there! The release that adds aXe!
=> Release 5.3.0

README.md
Adding nvm as node installer on README.md.
=> [#463] Adds nvm to readme.md as instruction to install node

bin/pa11y.js, package-lock.json, package.json, test/integration/cli/environment.test.js
Hi there! I've been using this project lately and decided to start contributing.  This PR is in reference to issue https://github.com/pa11y/pa11y/issues/483.
=> Improve environment flag

package-lock.json, package.json
Gives us lovely output like the following!
=> updates pa11y-axe-runner to 1.0.2

package-lock.json, package.json
Fixes a potential vulnerability in https-proxy-agent
Fixes #502.
=> Upgrade puppeteer to >=2.1.1

CHANGELOG.md, README.md, package.json
[#553](https://github.com/pa11y/pa11y/issues/553)
=> #553 Removed survey link from readme file

lib/reporters/csv.js, package-lock.json, package.json, test/unit/lib/reporters/csv.js
Removes the `pa11y-reporter-csv` dependency and merges the repo (with history) into here!
=> Merge reporter csv

lib/reporters/html.js, lib/reporters/report.html, package-lock.json, package.json, test/unit/lib/reporters/html.test.js, test/unit/mock/fs.js, test/unit/mock/hogan.js
Merges the html reporter (whoops, missed that) with it's history
=> Merge reporter html

lib/runners/axe.js, test/unit/lib/runners/axe.test.js
Since runners are merged into Pa11y, this will close the pending [PR](https://github.com/pa11y/pa11y-runner-axe/pull/19)
=> Removed mentions of section 508 from axe runner.

README.md
=> updated dead links to puppeteer docs

.github/workflows/publish.yml, .github/workflows/tests.yml
Also adds whitespace around actions to improve readability
=> Update checkout action to v5
