lib/sniff/handle-result.js, lib/sniff/run-html-codesniffer.js, test/unit/sniff/handle-result.js
This is basically a rebase of #56 against master plus adding some basic truncation.
=> Get and truncate the html source of messages from html_codesniffer

MIGRATION.md, README.md, lib/inject.js, reporter/cli.js, reporter/csv.js, reporter/html/result.html, test/integration/cli-config.js, test/integration/cli-ignore.js, test/integration/cli-level.js, test/integration/cli-reporter-csv.js, test/integration/cli-reporter-json.js, test/integration/cli-selector.js, test/integration/cli-standard.js, test/integration/mock/html/selectors.html, test/unit/lib/inject.js
Add the element's CSS selector to the results, completing #77 (css selectors were easier than XPath)
=> CSS Selectors

README.md, bin/pa11y, lib/pa11y.js, test/unit/lib/pa11y.js
We are using a customized fork of the HTML_CodeSniffer Library, so being forced to use the included one is a big step backwards for us.
=> Allow specificing the HTML_CodeSniffer Library location

MIGRATION.md, README.md, bin/pa11y, lib/pa11y.js, test/unit/lib/pa11y.js, test/unit/mock/phantom.js
Includes code from #81. @mfairchild365, do you fancy taking a look at this as well? Does it still suit your needs? One notable change is that I had to change the command-line flag to `-H` as `-h` was conflicting with `--help`.
=> Allow specifying the HTML CodeSniffer Library location

README.md, bin/pa11y, lib/inject.js, lib/pa11y.js, test/unit/lib/inject.js, test/unit/lib/pa11y.js
This allows for testing pages after client-side JavaScript has been run. It's not bullet-proof but works for now. Later we may enable execution of arbitrary scripts before the HTML CodeSniffer run which will be a more solid way to do this. Addresses #82.
@mfairchild365, happy with the implementation? Should it solve your issue?
=> Add an option which makes pa11y wait for a configured amount of time before running tests

README.md, reporter/markdown.js, test/integration/cli-reporter-markdown.js
Useful for generating reports that can be easily shared across GitHub Issues, Jekyll blogs, or anywhere else in the Markdown universe.
=> Add Markdown reporter

README.md
Hi, 
due to the general trickery of PhantomJS it can be, like the README.md states, hard to get `pa11y` or any other PhantomJS dependent cmd-line app to run on Windows. Even if you are able to successfully install PhantomJS and `npm`, you will most likely run into the following (pretty unhelpful) stacktrace:
``` bash
Error: spawn phantomjs ENOENT
at exports._errnoException (util.js:874:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
at onErrorNT (internal/child_process.js:344:16)
at doNTCallback2 (node.js:439:9)
at process._tickCallback (node.js:353:17)
at Function.Module.runMain (module.js:469:11)
at startup (node.js:134:18)
at node.js:961:3
```
The solution is trivial, but not exactly obvious: copying the binary version of `phamtomjs.exe` (or trying to get …
=> Add additional troubleshooting for using pa11y under Windows

lib/pa11y.js
This is necessary when we add our own standards and would like to use them. This is not a feature, this is kind of a bug fix :-).
Cheers!
=> Allow more standards. Do not hardcode the list

README.md, bin/pa11y, example/before-script/index.js, lib/pa11y.js, test/unit/lib/pa11y.js
This allows additional javascript to be run on the page before the pa11y
tests are run.
This will enable people to perform stuff such as page manipulations or
to login as a user before testing the page with pa11y.
=> Allows JavaScript to be run before running pa11y

README.md, bin/pa11y, lib/inject.js, lib/pa11y.js, test/integration/cli-hide-elements.js, test/integration/mock/html/hide-elements.html, test/unit/lib/inject.js, test/unit/lib/pa11y.js, test/unit/mock/window.js
This will allow areas of the page to be hidden before running HTML code
sniffer against the page. This relies on the fact that HTML code sniffer
will ignore anything thats `visibility` style is set to `hidden`.
The option accepts a string which allows for coma seperated selectors in
the same way as `querySelectorAll`.
e.g. "#modal, .adverts, div[data-hide]"
=> Adds the ability to hide elements from pa11y testing

README.md, reporter/cli.js, reporter/csv.js, reporter/html.js, reporter/json.js, reporter/markdown.js
This makes the built-in reporters usable with the JavaScript API. This should resolve #137.
=> Make the built-in reporters usable in JavaScript

README.md
Hope to answer the question of why pa11y gives different results to html codesniffer bookmarklet
=> Adds new question for pa11y html codesniffer

lib/inject.js, test/integration/cli-hide-elements.js, test/integration/mock/html/hide-elements.html, test/unit/lib/inject.js
The `hide-elements` options was broken due to a misunderstanding of how
`HTML_codeSniffer` worked.
This change moves away from relying on `HTML_codeSniffer` for this
feature and instead filters out errors that are unwanted.
=> Fixes the hide-elements options

README.md
We've hit the end of support date for Pa11y 1.x. Switching the emoji 👍💀
=> Deprecate Version 1.0

package.json
This fixed a security vuln with versions of minimatch older than
3.0.2. Minimatch is one of mocha's dependencies.
Older versions of minimatch (0.3.0 and 2.0.10, both vulnerable) are
still being pulled as dependencies of jshint. Jshint has fixed this
in master but a new version containing the fix hasn't been released
yet.
This shouldn't be much of a problem in production environments
anyway, as they are both devDependencies.
All the instances of `minimatch` in the dependencies after this fix:
```
$ npm list minimatch
pa11y@4.0.0 /Users/jose.bolos/repositories/pa11y/pa11y
├─┬ jscs@2.11.0
│ ├── minimatch@3.0.3
│ ├─┬ prompt@0.2.14
│ │ └─┬ utile@0.2.1
│ │   └─┬ rimraf@2.5.4
│ │     └─┬ glob@7.0.5
│ │       └── minimatch@3.0.3
│ └─┬ vow-fs@0.3.6
│   └─┬ glob@7.0.5
│     └── minimatch@3.0.3
├─┬ …
```
=> Upgrade mocha to version 3

lib/pa11y.js, test/unit/lib/pa11y.js
Using tlsv1 as default causes a problem on sites that have tlsv1
disabled (but support for example tls1.1 or tls1.2) as phantomjs
will fail to load the page without explanation.
Reverts #62
=> Remove ssl-protocol from default phantom config

CHANGELOG.md, lib/pa11y.js, package.json, test/unit/lib/pa11y.js
cc @lc512k @rowanmanning 
With `--debug` flag turned on, running `pa11y` will add to the debug logs the document title of the page tested.
This will allow user to ensure that passing tests are not false positives called from error pages which may not cause any pa11y errors/warnings while the actual page might. Naturally, this relies on the website being tested having appropriate document titles when a page errors (but given the variety of forms these may take it still requires human judgement to deduce whether test has been conducted on the intended page).
=> Display: Document title in debug mode

package.json
Avoids printing some warnings on `npm install` :warning:
=> Upgrade two devDependencies

README.md, bin/pa11y, lib/inject.js, lib/pa11y.js, test/unit/lib/inject.js, test/unit/lib/pa11y.js, test/unit/mock/window.js
cc @GlynnPhillips @rowanmanning @lc512k
Allows user to add a string of HTML that they expect to be included in the HTML of the page being tested to verify that the intended page is being tested (i.e. not an Application Error page) and/or certain elements are present on the page.
Next step is to add similar flag in `pa11y-ci` that can pass the option through into `pa11y`: https://github.com/pa11y/ci/pull/11.
=> Add: Verify page flag

README.md, example/actions/index.js, lib/action.js, lib/pa11y.js, test/unit/lib/action.js, test/unit/lib/pa11y.js
This is a proposal and working code for "actions", that should hopefully replace the use of `beforeScript` or provide a safer less error-prone alternative. I've added the ability to use predefined (by us) scripts to perform actions on the page before Pa11y runs tests:
```js
pa11y({
actions: [
'set field #username to exampleUser',
'set field #password to password1234',
'click element #submit',
'wait for path to be /myaccount'
]
});
```
I've added the following actions as a starting point. I'd like to get this in (tagged as a beta feature) then gather wider feedback from the community. I don't think we can predict which actions users need, but I've added enough to perform commonly requested tasks like logging in or clicking an element:
This allows you to click an element by passing in a CSS …
=> Add a proposal and working code for "actions", a new automation feature

README.md, lib/action.js, lib/pa11y.js, test/unit/lib/action.js, test/unit/lib/pa11y.js
Ideally we want to be able to check whether an action is valid before using it. This is especially useful in Pa11y webservice which would otherwise fail pretty much silently when an invalid action is encountered.
This adds the following method to pa11y:
```js
pa11y.validateAction('click element #submit');  // true
pa11y.validateAction('open the pod bay doors'); // false
```
=> Expose action validation (for use in webservice)

README.md, lib/action.js, test/unit/lib/action.js
This updates the `wait-for-url` action to allow test execution to be paused until the page does **not** match a given fragment, path, or URL if "to not be" is included in the action expression as discussed in [#228](https://github.com/pa11y/pa11y/issues/228#issuecomment-275021330).
=> Add negated version of "wait-for-url" action

TROUBLESHOOTING.md
As we've had two issues already mentioning this error (#175 and #270) I thought that it would be a good idea to add it to the troubleshooting guide in order to clarify that it's not a problem with pa11y itself, and that there's not much that we can do about problems with phantomjs.
I'm not extremely happy with the wording, so feel free to suggest any improvements.
=> Add phantom exit code 127 to troubleshooting guide

bin/pa11y, test/integration/helper/describe-cli-call.js
The old `bin/pa11y` file was just an alias for `bin/pa11y.js`, and was
only present for backwards compatibility in case people were referring
to it explicitly.
I think it's been long enough that we can remove this now.
=> Remove the old pa11y command

.travis.yml, README.md, package.json
This removes support for Node.js < 8, as we'll need to use async and
await for Headless Chrome support. I've linked to a currently
non-existant 4.x branch for anybody who needs support for older
versions, and I imagine we'll be maintaining 4.x for a year or so.
=> Support only Node.js 8+

README.md
the main two themes i'm seeing with the survey so far is that people find the CLI complicated by nature, and that people would like stuff like tutorials. So I've: 
* added a plug for Koa11y 
* added a section for Pa11y tutorials/article to the repo
I'll add the other tool-specific articles to the other repos.
=> add tutorials and links

README.md, lib/pa11y.js, test/unit/lib/pa11y.js
This updates the `pa11y` function to support callbacks if an end user
prefers to use these over promises.
This resolves #305
=> Support callbacks

README.md, bin/pa11y.js, lib/runner.js, test/unit/lib/runner.js
This was bugging me, as we have a situation where we'd have to refer to
`message.message`. We're now referring to the things that HTML
CodeSniffer sends back as "issues". I think it's more descriptive too.
=> Rename "messages" to "issues"

MIGRATION.md, README.md, bin/pa11y.js, lib/pa11y.js, test/integration/cli/actions-check-field.js, test/integration/cli/actions-click-element.js, test/integration/cli/actions-set-field-value.js, test/integration/cli/actions-wait-for-element-state.js, test/integration/cli/actions-wait-for-url.js, test/integration/cli/add-rule.js, test/integration/cli/config.js, test/integration/cli/exit-codes.js, test/integration/cli/hide-elements.js, test/integration/cli/ignore.js, test/integration/cli/output.js, test/integration/cli/reporter-csv.js, test/integration/cli/reporter-json.js, test/integration/cli/root-element.js, test/integration/cli/standard.js, test/integration/cli/wait.js, test/unit/lib/pa11y.js
We now ignore warnings and notices by default, they get added into the
ignore array once all the options have been defaulted.
I've added a way to continue including them if people want that, this is
just a change in the default behaviour.
Resolves #170
=> Ignore warnings and notices by default

bin/pa11y.js, package.json
This backports the reporter compatibility check from Pa11y 5.x. Pa11y
4.x will now output a useful error if you try to use a reporter which
only supports Pa11y 5 and above.
=> Backport the reporter compatibility check

lib/pa11y.js, test/unit/lib/pa11y.js, test/unit/mock/util.js
This is possible now that we're using Headless Chrome. This should aid
Pa11y users (and us) in debugging issues.
Resolves #233
=> Output browser console messages to the debug log

README.md, lib/action.js, test/integration/cli/actions-screen-capture.js, test/integration/mock/config/actions-screen-capture.json, test/unit/lib/action.js
This allows a Pa11y user to verify that the page looks correct at different points in the test run.
=> Add an action to capture a screen-grab

README.md
https://github.com/pa11y/pa11y-reporter-1.0-json has now been deprecated, so removing it from this README.
=> Remove reference to deprecated pa11y 1.0 reporter

README.md, lib/action.js, test/unit/lib/action.test.js
We have a case where we are using the existing actions to log into an app by filling in fields and clicking submit buttons. Once logged in the app redirects to a landing page but this is not the page we want to run Pa11y against. There is another page, that you need to be authenticated to view (hence the logging in steps), that you can't get to directly from the landing page.
This new 'redirect' action e.g. "redirect to http://pa11y.org/" allows us to specify a new url to goto once our login actions have finished running.
Hopefully useful for others with similar circumstances...
=> Adding a new action for redirecting to a specified url

lib/pa11y.js, test/unit/lib/pa11y.test.js
I think the browser console logging was broken with the update to
Puppeteer 1.0.0 - the API has changed and I didn't spot that. I've
updated and now this logs the message as expected rather than a full
ConsoleMessage object.
=> Fix browser logging

README.md, lib/pa11y.js, test/unit/lib/pa11y.test.js
This PR adds the ability to pass in a Puppeteer Browser instance to be
shared across multiple Pa11y test runs, this should be less resource
intensive and we need this work in place for Pa11y CI and probably
Sidekick.
I've added some warnings to the README for anyone using this themselves,
but mostly I think it'll be used by our own derivative projects.
Resolves #298
=> Allow sharing a Chrome browser instance

lib/pa11y.js, test/unit/lib/pa11y.test.js, test/unit/mock/puppeteer.mock.js
This PR aims to achieve 2 main issues
1.- I noticed that if the actions part of the test fails the whole function will throw and the promise will be rejected, causing the process to end and close the browser, however its impossible to access the page at that point. This PR makes it so I can take screenshots of the page when errors are thrown because I would own the page.
2.- Also noticed that if the browser passed then the page created by the test will never close and would hoard memory. Causing long-lasting browser instances to keep these pages running forever.
=> Support `options.page`

lib/runner.js
This fixes the common error `_runPa11y is not defined`. This is caused
when a page that's being tested includes a global `module.exports`
property. It seems Pa11y was getting into a race condition with the
site's JavaScript code - if Pa11y loaded first, it was fine. If it
loadded second, then it would add the Pa11y code to `module.exports`
rather than `window`.
This fixes #392. Thanks to @jakechampion for the suggestion
=> Fix the _runPa11y not defined error

README.md
Adds a line to the README to clarify what happens if you try to test a root element that isn't there. 
Relates to https://stackoverflow.com/questions/50130152/accessibility-testing-using-pa11y-5-on-a-page-with-popup-overlay/50153618#50153618
It would be worth outputting a notice in the debug log if the root element isn't found. I might even open a PR for it later ;)
=> Clarify rootElement behaviour

README.md
The html and tsv transformers have switched to using `results` as the function call, no longer `process`
=> docs: fix function call for transformers

lib/pa11y.js, test/unit/lib/pa11y.test.js
Since the `page.setRequestInterception` method of puppeteer's Page is buggy (there are some relevant issues [here](https://github.com/GoogleChrome/puppeteer/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+setRequestInterception)), I think it is better avoid to use it until it is necessary (eg for POST page requests).
In our case, intercepting requests totally breaks the page :(
=> Intercept first page requests only when necessary

README.md
The directory in the screen capture path must exist for a
screen capture to be saved. This is Puppeteer behaviour,
but we weren't documenting anywhere
=> Clarify the screen capture option

lib/action.js, test/unit/lib/action.test.js
This is a fix for #396 
The reason for the problem is the value part of the regex (`(.+)`) matches anything. However fragment, hash, host, path or url can contain spaces.
Thus `([^\s]+)` can happily grab that without greedily ignoring spaces.
=> Remove spaces from being part of a wait actions value (#396)

README.md, package-lock.json
Current matcher for "set field" uses a greedy regular expression which will continue matching a selector all the way up to the last occurrence of " to ". However, this might occur within a value (the final desired capture group) and the matches will be performed incorrectly.
Using the non-greedy .+? will instead attempt to find the shortest match which satisfies the overall expression.
There is a small(er) risk that a desired selector contains a custom element named 'to' but I deem this to be far less likely than wanting ` to ` appearing in a desired input value.
referencing issue #452
=> 452: "set field" to use non-greedy regexp

README.md
Uses the dynamic URL that looks up the supported Node.js versions on npm.
Resolves https://github.com/pa11y/pa11y/issues/470.
=> docs: update the badge URL for the Node.js version

README.md, bin/pa11y.js, lib/pa11y.js, lib/runner.js, package-lock.json, package.json, test/unit/lib/pa11y.test.js, test/unit/lib/runner.test.js, test/unit/mock/semver.mock.js
We now support both the aXe and HTML CodeSniffer test runners - You can
run Pa11y using one or both of these. I've done this by untangling HTML
CodeSniffer from the core code and writing two new modules:
- https://github.com/pa11y/pa11y-runner-axe
- https://github.com/pa11y/pa11y-runner-htmlcs
These come bundled with Pa11y so there's no need to install separately
for now. They'll be considered stable when we're ready to release the
code on this branch.
Looking for code review but also for people to test this work out.
Install the in-progress version with:
```
npm install -g git+ssh://git@github.com:pa11y/pa11y.git#multiple-test-runners
```
Test with HTML CodeSniffer (same as now):
```
pa11y https://www.example.com/
```
Test with aXe:
```
pa11y --runner axe https://www.example.com/
``` …
=> Support aXe test runner

test/unit/lib/pa11y.test.js
Adds three new tests to fill some missing branches. Results in 100% code coverage 💃 
The tests added are all checks that an action is **not** taken
- `setUserAgent` isn't called if no user agent is passed
- The interception handler only triggers on the first intercepted request (the main HTTP GET)
- Doesn't navigate the puppeteer page if `ignoreUrl` is true
=> Add missing tests

lib/pa11y.js
From the [puppeteer docs about setViewport](https://github.com/GoogleChrome/puppeteer/blob/387a53270762cd1a3e7db1c156275231655b1b10/docs/api.md#pagesetviewportviewport):
> In certain cases, setting viewport will reload the page in order to set the isMobile or hasTouch properties.
> A lot of websites don't expect phones to change size, so you should set the viewport before navigating to the page.
This hasn't caused any problems that we know of, but we probably want to avoid this behaviour.
=> Invert the order of setViewport and goto

CHANGELOG.md
Release the alpha of pa11y 6 - it will be tagged as `next` in npm so users will only download this version of pa11y if they intend to.
This will allow us to test the preliminary support for WCAG 2.1 early without breaking anything.
Once we know everything is working, I'll update the migration guide before the official 6.0 release.
=> Version 6.0.0-alpha

lib/option.js, lib/pa11y.js, test/unit/lib/option.test.js
Extracts the functions in `lib/pa11y` related to argument parsing and option processing (`parseArguments`, `verifyOptions`, `defaultOptions` and `sanitizeUrl`) to a separate module.
Only `parseArguments` and `verifyOptions` function is used somewhere else, so the module has a clean, simple interface.
No changes to the existing tests were necessary in order for them to pass, but I've extracted the parts of the tests related to these options to their own file.
=> Extract option functions to a new separate module

TROUBLESHOOTING.md
PhantomJS is not used anymore since v5, so having it there will only confuse people.
Closes #560.
=> Remove reference to PhantomJS from troubleshooting

README.md
The URL has been changed from [this](https://squizlabs.github.com/HTML_CodeSniffer/) to [new one](https://squizlabs.github.io/HTML_CodeSniffer/).
=> HTML CodeSniffer URL updated in README with the working one.

bin/pa11y.js, lib/reporters/cli.js, package-lock.json, package.json, test/unit/lib/reporters/cli.js, test/unit/mock/kleur.js
Merges the pa11y-reporter-cli repo into pa11y, preserving the git history of the reporter.
The only change required to pa11y to support this is to first check ../lib/reporters/${name} for the reporter. The reporter itself has intentionally not been changed at all, however once all reporters are merged we can drop the version bits and bobs and speed up how we load the internal reporters (i.e. keep a map of internal reporters which we can require directly without a try/catch).
=> Merge reporter cli

package-lock.json, package.json, test/.eslintrc.js
Update all dependencies and devDependencies to the latest versions. The only exception is `commander` which is still on `6.2.1` as there's a breaking change in 7.0 which requires code changes. I've created #580 to fix that.
Also bumps the minimum Node.js version supported to the oldest supported LTS (v12).
=> Update all deps and devDeps to latest versions

README.md
* Add extended TOC
* Remove `beta` label from and notice
* Format all headings in the same way
* Format all lists in the same way
* Unify the Node.js installation instructions for Linux and macOS for simplicity
* Remove Node.js installation instructions for Windows 7
* Update support table
* Replace HTTP with HTTPS throughout the whole document
* Replace the links in the tutorials section with a link to the tutorial page where we have more resources
* Add language to all code blocks
* Remove unused reference to JSON reporter 1.0
* Update build status badge and info
* Update copyright year
=> Update README for v6

MIGRATION.md
Also reformats the document so it matches the format suggested by markdownlint and used by other documents in the repo.
=> Add 6.0 to the migration guide

lib/pa11y.js, lib/runners/axe.js, lib/runners/htmlcs.js, package-lock.json, package.json, test/integration/cli/exit-codes.test.js, test/unit/lib/pa11y.test.js, test/unit/lib/runners/axe.test.js, test/unit/lib/runners/htmlcs.test.js, test/unit/mock/fs.mock.js
Merges both `htmlcs` and `aXe` runners into the repo with their full git histories.
The only substantial change is the removal of using `async` to load the runner scripts and instead opting for `fs.readFileSync` which makes little change given we were loading the runners in a loop and `await`'ing on each read anyway. This results in simplified loading logic and removes a problem when running the tests with coverage 🎉
=> Merge runners

lib/reporters/csv.js, test/integration/cli/reporter-csv.test.js
Handles when HTML_CodeSniffer returns null for the context (with the newer `npm` version) and returns an empty string instead.
Fixes https://github.com/pa11y/pa11y-reporter-csv/issues/1
=> Handles null context in csv reporter

bin/pa11y.js, test/integration/cli/environment.test.js
This updates the `--environment` CLI output to include the actual `pa11y` version from package.json, and updates the corresponding integration test to check for pa11y output (closes #577).
=> Update --environment CLI output to include pa11y version

lib/option.js, test/unit/lib/option.test.js, test/unit/mock/fs.mock.js
Per #576 attempting to detect valid local paths before deciding to use `http://` scheme
Changed some style and coverage within tests as well. I do not believe that `options` needs to be re-required within the test, and in fact we can import the functions we need directly, just once.
=> 576: check local paths when parsing options

README.md
1. [HTML Code Sniffer WCAG2AAA](https://github.com/pa11y/pa11y/wiki/HTML-CodeSniffer-Rules) ruleset link updated with the [Squizlab's ruleset](https://squizlabs.github.io/HTML_CodeSniffer/Standards/WCAG2/).
2. Will delete the wiki page once this PR is merged.
=> Replaced WCAG 2.0 mentions with WCAG 2.1, ruleset link updated.

README.md, bin/pa11y.js, test/integration/cli/reporter-cli.test.js, test/integration/cli/reporter-csv.test.js, test/integration/cli/reporter-html.test.js, test/integration/cli/reporter-tsv.test.js, test/integration/mock/config/reporter-cli.json, test/integration/mock/config/reporter-csv.json, test/integration/mock/config/reporter-html.json, test/integration/mock/config/reporter-tsv.json
Closes #615 
- Update README for HTML reporter
- Add `html` reporter CLI option to [`loadReporters`](https://github.com/pa11y/pa11y/blob/60cde76db60431753b8258dfd6be4bf55c98463f/bin/pa11y.js#L202) 
- Update csv reporter integration test to include config case
- Add integration tests for TSV reporter option
- Add integration tests for HTML reporter option
- Add integration tests for CLI reporter option
=> HTML reporter fix and reporter integration test cleanup

.github/workflows/tests.yml, package-lock.json, package.json
Update dependencies to latest versions, including Puppeteer, to resolve issues with Ubuntu 22.04, which is [now `ubuntu-latest` for GitHub actions](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/). Closes https://github.com/pa11y/pa11y/issues/662 and https://github.com/pa11y/pa11y/issues/651.
- Update tests to latest Node releases - BREAKING
- Drop v12 (EOL 2022-04-30), v14 (EOL 2023-04-30), v16 (EOL 2023-09-11)
- Skip v19 (EOL 2023-06-01)
- Add v18 and v20
- Update to lockfile v2
- Update to latest devDependencies (`eslint`, `eslint-plugin-jest`, `jest`)
- Update dependencies with patch updates (`kleur`)
- Update dependencies with minor updates (`axe-core`, `semver`)
- Update dependencies with major updates (`puppeteer`, `commander`) …
=> Update dependencies to resolve Ubuntu issues

.github/workflows/tests.yml, lib/option.js, lib/pa11y.js, package.json, test/integration/global-setup.js, test/integration/helper/pa11y-cli.js, test/integration/mock/website.js, test/integration/setup-env.js, test/unit/lib/option.test.js, test/unit/lib/pa11y.test.js, test/unit/lib/runners/htmlcs.test.js
This PR merges the changes already present in `next` into the default branch, another step towards releasing `pa11y@7`.
1. Supports `push` to `main` in preparation for next build on `main` when merged, part of:
https://github.com/pa11y/org/issues/19
1. Some renaming, and also removal of naming and comments where content was descriptive
1. Require new jobs in matrix to pass
1. Rename default branch to `main` from `master`
By @aarongoldenthal and @josebolos in:
- #647 
1. Add Windows and macOS to GA matrix
1. Set test-specific environment variables within Jest setup
1. Move env var to global since needed there and run before setup
1. Update path resolution to be platform independent, and fix issues
1. Update cli runner to call node since Windows ignores the shebang in bin
1. Increase …
=> Support macOS and Windows (absorb `next`)

.github/workflows/publish.yml
This PR adds a publishing workflow.  See https://github.com/pa11y/pa11y-lint-config/pull/6.  This is a duplicate of that implementation; the YAML may be centralised later if no need for differentiation emerges.
=> Add publishing workflow

.github/workflows/tests.yml, CHANGELOG.md, MIGRATION.md, README.md, TROUBLESHOOTING.md, package-lock.json, package.json, test/integration/cli/actions-wait-for-element-event.test.js, test/integration/setup-env.js
This PR upgrades `axe-core` and all but two other dependencies to their current latest versions.  It is currently expected to be the final change of behaviour before Pa11y 7's PR.
1. Upgrade to [`axe-core 4.8.2`](https://github.com/dequelabs/axe-core/blob/develop/CHANGELOG.md) from `4.7.0`
1. Upgrade to the recently published [`pa11y-lint-config 3`](https://github.com/pa11y/pa11y-lint-config/releases/tag/3.0.0) from `2`
1. Upgrade several other packages.  Where these are major version upgrades, the 'breaking' changes were often in their Node.js requirements.  For example here's [`bfj's changelog`](https://gitlab.com/philbooth/bfj/-/blob/master/HISTORY.md)
1. Fix one flaky test in GA by extending the Jest timeout
1. Upgrade Puppeteer to `20` from `19`; an upgrade to version `21` is not yet …
=> Upgrade `axe-core` and all but two other dependencies to latest; use new support policy

test/integration/cli/exit-codes.test.js, test/integration/cli/wait.test.js, test/integration/mock/html/actions-wait-for-element-event.html
This PR:
1. resolves (hopefully resolves) the test flake that has frequently been causing this test to fail on `macos-latest` in GitHub Actions.  Hypothesis: Puppeteer was dispatching the event before having its listener in place.
1. increases the `--wait` test's legroom from 100ms to 500ms since that has failed occasionally too 
1. reinstates the `notahost` test, since it works in GitHub Actions
Thanks for the nudge @aarongoldenthal
=> Fix flake affecting `wait-for-element-event` integration tests

lib/pa11y.js, test/unit/lib/pa11y.test.js
It appears some of the reporter loading/validation logic was copied to support runners, but some "reporter" references were overlooked. This cleans up the runner loading/validation logic and tests to properly reference `runner` instead of `reporter`.
=> Clean up nomenclature to properly reference runner, not reporter

MIGRATION.md, bin/pa11y.js, lib/pa11y.js, package-lock.json, package.json, test/unit/mocks/puppeteer.mock.js
Pa11y 7.0.0 depends on `puppeteer` 20.9.0, which is already deprecated (with all versions prior to 21.5.0). This PR updates `puppeteer` to the latest supported version, and also updates all other dependencies.
- `dependencies`:
- Update `axe-core` from 4.8.2 to 4.8.4
- Update `commander` from 11.1.0 to 12.0.0 (minor refactor for breaking changes)
- Update `puppeteer` from 20.9.0 to 22.3.0
- Changed `page.removeListener` to `page.off` (the `addListener`/`removeListener` methods were removed in `puppeteer@22.0.0` per [puppeteer/puppeteer#11792](https://github.com/puppeteer/puppeteer/pull/11792), and `page.on` is already used to add all listeners)
- Update the migration guide for _new_ headless as the default in puppeteer 22. This assumes a major update to pa11y 8)
- Note: this updates …
=> Update puppeteer to latest supported version (and other dependency updates)

lib/pa11y.js, package-lock.json, package.json, test/integration/cli/timeout.test.js, test/unit/lib/pa11y.test.js
Replace the use of [p-timeout](https://github.com/sindresorhus/p-timeout) with Node's native [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout_static) (Node 15+), given we can no longer update `p-timeout` beyond version 4 due to [the author's stance](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) on ESM and CommonJS.  Parity is maintained with the previous implementation.
1. Remove dependency `p-timeout`.
2. In this PR's revision the recipient of the `AbortSignal` does not interact with or listen to it, but this implementation still achieves parity with the previous version.
3. Remove the unit test of the calls to the dependency, without replacing it.  This test was closely tied to the implementation and the behaviour is covered by …
=> Use native `AbortSignal` in place of `p-timeout`

.github/workflows/tests.yml, CHANGELOG.md, MIGRATION.md, README.md, lib/reporters/cli.js, lib/reporters/csv.js, lib/reporters/html.js, lib/reporters/json.js, lib/reporters/tsv.js, lib/runners/axe.js, lib/runners/htmlcs.js, package-lock.json, package.json
=> Release `pa11y@9.0.0`

TROUBLESHOOTING.md
This PR adds a `TROUBLESHOOTING.md` note on AppArmor workarounds with Ubuntu 23.10+. Comments come as the result of discussion in #724 (thank you @aarongoldenthal!).
Closes #724
=> Add troubleshooting note on AppArmor workarounds with Ubuntu 23.10+

README.md
Current requirements is specific to v8. Updates docs to reflect v9 Node requirements based off [this table](https://github.com/pa11y/pa11y?tab=readme-ov-file#support-and-migration).
=> docs(README.md): updates node requirements for pa11y v9
